steps:
  - label: ":shell: Tests"
    plugins:
      docker-compose#v2.2.0:
        run: tests

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v1.0.0:
        name: docker-login